services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:Hannah@143@host.docker.internal:5432/learning
      - AUTH_TRUST_HOST=true
    # This maps your local folder to the container's app folder
    volumes:
      - .:/app
      # This prevents your local node_modules from overwriting the container's node_modules
      - /app/node_modules
    tty: true