export interface Course {
  id: string
  topicId: string
  name: string
  description: string
  instructor: string
  level: 'beginner' | 'intermediate' | 'advanced'
  duration: string
  rating: number
  enrolledCount: number
  lessonsCount: number
}

export const courses: Course[] = [
  // Science
  {
    id: 'sci-1',
    topicId: 'science',
    name: 'Introduction to Physics',
    description: 'Learn the fundamental principles of physics from kinematics to energy',
    instructor: 'Dr. Sarah Chen',
    level: 'beginner',
    duration: '8 weeks',
    rating: 4.8,
    enrolledCount: 2543,
    lessonsCount: 24,
  },
  {
    id: 'sci-2',
    topicId: 'science',
    name: 'Organic Chemistry Basics',
    description: 'Master the essential concepts of organic chemistry and molecular structures',
    instructor: 'Prof. James Miller',
    level: 'intermediate',
    duration: '10 weeks',
    rating: 4.6,
    enrolledCount: 1876,
    lessonsCount: 28,
  },
  {
    id: 'sci-3',
    topicId: 'science',
    name: 'Human Biology Essentials',
    description: 'Explore the systems and functions of the human body',
    instructor: 'Dr. Emma Wilson',
    level: 'beginner',
    duration: '6 weeks',
    rating: 4.7,
    enrolledCount: 3124,
    lessonsCount: 20,
  },

  // Math
  {
    id: 'math-1',
    topicId: 'math',
    name: 'Calculus Fundamentals',
    description: 'Understand limits, derivatives, and integrals from the ground up',
    instructor: 'Dr. Michael Roberts',
    level: 'intermediate',
    duration: '12 weeks',
    rating: 4.5,
    enrolledCount: 1654,
    lessonsCount: 32,
  },
  {
    id: 'math-2',
    topicId: 'math',
    name: 'Linear Algebra for Machine Learning',
    description: 'Essential linear algebra concepts used in modern ML applications',
    instructor: 'Prof. Lisa Wong',
    level: 'advanced',
    duration: '8 weeks',
    rating: 4.9,
    enrolledCount: 4231,
    lessonsCount: 26,
  },
  {
    id: 'math-3',
    topicId: 'math',
    name: 'Geometry and Trigonometry',
    description: 'Master geometric shapes, angles, and trigonometric functions',
    instructor: 'Dr. Robert Taylor',
    level: 'beginner',
    duration: '7 weeks',
    rating: 4.4,
    enrolledCount: 987,
    lessonsCount: 22,
  },

  // Programming
  {
    id: 'prog-1',
    topicId: 'programming',
    name: 'Python for Beginners',
    description: 'Learn Python programming from scratch with hands-on projects',
    instructor: 'Alex Kumar',
    level: 'beginner',
    duration: '6 weeks',
    rating: 4.8,
    enrolledCount: 5432,
    lessonsCount: 24,
  },
  {
    id: 'prog-2',
    topicId: 'programming',
    name: 'Advanced JavaScript',
    description: 'Deep dive into ES6+, async programming, and advanced patterns',
    instructor: 'Sofia Perez',
    level: 'advanced',
    duration: '10 weeks',
    rating: 4.7,
    enrolledCount: 2876,
    lessonsCount: 30,
  },
  {
    id: 'prog-3',
    topicId: 'programming',
    name: 'Web Development with React',
    description: 'Build modern web applications with React and Next.js',
    instructor: 'David Lee',
    level: 'intermediate',
    duration: '8 weeks',
    rating: 4.9,
    enrolledCount: 3654,
    lessonsCount: 28,
  },

  // Language
  {
    id: 'lang-1',
    topicId: 'language',
    name: 'Spanish for Beginners',
    description: 'Start your Spanish learning journey with essential vocabulary and grammar',
    instructor: 'Maria Garcia',
    level: 'beginner',
    duration: '8 weeks',
    rating: 4.6,
    enrolledCount: 2341,
    lessonsCount: 26,
  },
  {
    id: 'lang-2',
    topicId: 'language',
    name: 'French Intermediate',
    description: 'Build on your French foundation with conversational skills',
    instructor: 'Jean Dubois',
    level: 'intermediate',
    duration: '10 weeks',
    rating: 4.5,
    enrolledCount: 1432,
    lessonsCount: 28,
  },
  {
    id: 'lang-3',
    topicId: 'language',
    name: 'English Fluency Mastery',
    description: 'Achieve native-like fluency in spoken and written English',
    instructor: 'Thomas Anderson',
    level: 'advanced',
    duration: '12 weeks',
    rating: 4.8,
    enrolledCount: 1876,
    lessonsCount: 32,
  },

  // Finance
  {
    id: 'fin-1',
    topicId: 'finance',
    name: 'Personal Finance Essentials',
    description: 'Learn budgeting, savings, and investment fundamentals',
    instructor: 'Rebecca Johnson',
    level: 'beginner',
    duration: '6 weeks',
    rating: 4.7,
    enrolledCount: 3215,
    lessonsCount: 18,
  },
  {
    id: 'fin-2',
    topicId: 'finance',
    name: 'Stock Market Investing',
    description: 'Understand stock valuation and build a successful investment portfolio',
    instructor: 'Mark Thompson',
    level: 'intermediate',
    duration: '8 weeks',
    rating: 4.6,
    enrolledCount: 2104,
    lessonsCount: 24,
  },
  {
    id: 'fin-3',
    topicId: 'finance',
    name: 'Cryptocurrency & Blockchain',
    description: 'Explore digital assets and blockchain technology fundamentals',
    instructor: 'Chris Kumar',
    level: 'advanced',
    duration: '7 weeks',
    rating: 4.5,
    enrolledCount: 1543,
    lessonsCount: 20,
  },

  // History
  {
    id: 'hist-1',
    topicId: 'history',
    name: 'Ancient Civilizations',
    description: 'Journey through Egypt, Greece, Rome, and ancient Asia',
    instructor: 'Dr. Elizabeth Barrett',
    level: 'beginner',
    duration: '8 weeks',
    rating: 4.8,
    enrolledCount: 2876,
    lessonsCount: 24,
  },
  {
    id: 'hist-2',
    topicId: 'history',
    name: 'Medieval Europe',
    description: 'Explore the kingdoms, cultures, and transformations of medieval Europe',
    instructor: 'Prof. William Hughes',
    level: 'intermediate',
    duration: '9 weeks',
    rating: 4.5,
    enrolledCount: 1654,
    lessonsCount: 26,
  },
  {
    id: 'hist-3',
    topicId: 'history',
    name: 'World War II: A Global Perspective',
    description: 'Comprehensive study of WWII from multiple continents and viewpoints',
    instructor: 'Dr. Michael Castro',
    level: 'intermediate',
    duration: '10 weeks',
    rating: 4.9,
    enrolledCount: 3421,
    lessonsCount: 30,
  },
]
